spring:
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: 12345678
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: 6318d3d8-9501-4a1c-b95f-cb99265bd8d2
  expiration: 900000  #miliseconds